name: ml
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alembic=1.13.3
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.9.1
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.9.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.5
  - cryptography=38.0.1
  - cycler=0.11.0
  - databricks-cli=0.17.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docker-py=6.1.3
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - fftw=3.3.9
  - flask=2.2.5
  - fonttools=4.25.0
  - freetype=2.12.1
  - future=0.18.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - greenlet=3.1.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libpng=1.6.37
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.3
  - mako=1.2.3
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mlflow=1.30.0
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.5.0
  - nest-asyncio=1.5.5
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - oauthlib=3.2.2
  - openssl=1.1.1w
  - packaging=21.3
  - pandas=1.5.1
  - pandocfilters=1.5.0
  - paramiko=3.5.0
  - parso=0.8.3
  - patsy=0.5.6
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - prometheus_client=0.14.1
  - prometheus_flask_exporter=0.22.4
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=4.25.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.10.1
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.1
  - pywin32-on-windows=0.1.0
  - pywinpty=2.0.2
  - pyyaml=6.0.2
  - pyzmq=23.2.0
  - querystring_parser=1.2.4
  - requests=2.28.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.13.2
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sip=4.19.13
  - six=1.16.0
  - smmap=4.0.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.51
  - sqlite=3.39.3
  - sqlparse=0.5.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - tabulate=0.9.0
  - terminado=0.13.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022f
  - urllib3=1.26.12
  - vc=14.2
  - vs2015_runtime=14.42.34433
  - waitress=2.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=3.1.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - cloudpickle==2.2.1
    - commonmark==0.9.1
    - cp-common==0.1.9.1
    - gym==0.26.2
    - gym-notices==0.0.8
    - loguru==0.6.0
    - pyarrow==20.0.0
    - pywin32==311
    - rich==12.6.0
    - win32-setctime==1.2.0
